name: End-to-End Tests

on:
  pull_request:
    branches: [develop, master]
    paths: ['frontend/**', 'backend/**']

jobs:
    e2e-tests:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Checagem do codigo
              uses: actions/checkout@v4

            - name: Instalar Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '21'

            - name: Instalar dependencias do backend
              working-directory: backend
              run: npm install

            - name: Rodar backend
              working-directory: backend
              env:
                MONGODB_URI: ${{ secrets.MONGODB_URI }}
              run: npm run build && npm start &

            - name: Aguardando backend iniciar
              run: sleep 10 && npx wait-on http://localhost:3000/api/users --timeout 60000 --interval 2000
               
            - name: Instalando dependencias do frontend
              working-directory: frontend
              run: npm install

            - name: Rodar testes e2e
              working-directory: frontend
              run: npm run test:run