name: Front-end CD Pipeline

on:
  push:
    branches: [master]
    paths:
      - "front-end/**"
      - ".github/workflows/front-cd.yml"

jobs:
  frontend-cd:
    runs-on: ubuntu-latest
    environment: prod

    steps:

      - name: Buscando o codigo
        uses: actions/checkout@v4

      - name: Configurando o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Instalando dependencias
        working-directory: front-end
        run: npm ci

      - name: Buildando o projeto
        working-directory: front-end
        run: npm run build
      
      - name: Configurando AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Configurando o S3
        run: aws s3 sync ./front-end/dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidando o CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
      
        
          
        

